### PR TITLE
Feat pytest

### PR DESCRIPTION
**Pull request by ppxasjsm**
Main features that were added:
- move from nose to pytest
- remove pyqt4 dependency
- allow support with networx2 and rdkit (2018.01), however it does result in a deprecation warning that should be addressed soon. 
-versioneer added for automated versioning of new release
- travis rewrite 
The latest build passes.

### CODE REVIEW

**Comment by ppxasjsm** [comment]
@davidlmobley could you have a look at this? The build shouldn't be failing and I have just rerun the Travis build and it worked fine.

**Comment by davidlmobley** [comment]
Sorry for the delay, was tied up with grant deadlines. You mean it seems to be passing so you want to get it reviewed so we can merge?

I'm in the same place as @nividic at the moment so I'll see if he wants to have a look.

**Comment by davidlmobley** [comment]
@nividic says he will look at it.

**Comment by ppxasjsm** [comment]
@nividic Any thoughts on this? I would really like to generate a release based on this. We can then happily move on by dissecting it completing and making very drastic changes, but it would be good to have this version set as something like 0.1. Let me know what you think.

**Review by nividic — COMMENTED** [review]
@davidlmobley @ppxasjsm I would like to add here the automatic upload to conda when the travis test is passed (we can do it in another release).

**Review by nividic — DISMISSED** [review]
You have removed a lot of tests here....e.g. the argument checking, graph generation, radial graph generation etc.

**Review by nividic — APPROVED** [review]
@ppxasjsm @davidlmobley it look good to me. Thanks for all the cleaning and improvements.

**Comment by nividic** [comment]
@ppxasjsm In the end I think you have removed some of the tests e.g. graph_generation...are you going to put them back?

**Comment by ppxasjsm** [comment]
@nividic yeah I have added most of the tests back in. There is definitely room for more tests, but basically, I would like to just get a release of the current state since I used it in the D3R challenge, so I can reference the version in the writeup. Then we can go wild and plan changes for future updates etc.

Thinking of a 0.1 release or something along those lines, and then adhere to some pep8 version numbering convention as I doubt it would make sense for us to go with versioning including release years, as we are unlikely to release that often.  

As for the conda install. This would be an added bonus, but can be done later? I would do a pypi release for sure and then people can install it with pip even in a conda environment. 
We have been having some nightmares with conda and resulting dependency updates, so I would like to spend a bit of careful time making sure the conda recipe really only includes the necessary dependencies.

**Comment by ppxasjsm** [comment]
The travis was passing. Not sure why it wasn't before. I made one type changed and pushed it and it should hopefully be fine?

**Pull request merged**
