### PR TITLE
[WIP] Refactor

### PR DESCRIPTION
**Pull request by halx**
First attempt at refactoring the code. Primary goals: emphasis on the rules and make it easily replacable if later needed, good OOP practice, keep and eye on useful API.

### CODE REVIEW

**Comment by halx** [comment]
First attempt at refactoring the code.  Primary goals: emphasis on the rules and make it easily replacable if later needed, good OOP practice, keep and eye on useful API.

**Comment by davidlmobley** [comment]
It'll be a while before I get to look at this in any detail and I'm fairly far removed from the code at this point anyway (I'm up on the science of what it should be doing but not the code), so I've asked @nividic to take a look at the code, discuss any philosophical issues with me, and we'll get back to you.

**Comment by davidlmobley** [comment]
@halx - Gaetano and I just discussed. He has some issues he'll bring up, and I have a couple as well:
1. **Is it worth an OpenBabel dependency?** This introduces a dependency on OpenBabel, (a) for supporting additional file formats as inputs, and (b) for getting INCHI keys as molecular identifiers. Do you see a major need to support a variety of input file formats? Presumably if someone is going to go on to free energy calculations they are going to have to go through something like .mol2 or .sdf anyway, or is this important for FESetup? (Previously, you raised the issue of the number of dependencies so we were just curious if the benefit here is worth introducing another dependency.)
2. **What molecular identifiers should we use?** Regarding INCHI keys as molecular identifiers - I can see some benefits of introducing identifiers like SMILES or INCHI keys which have (potentially) a 1:1 correspondence to particular molecules as this would allow detection of trouble cases such as where a user inputs the same molecule multiple times, etc. However, typically I prefer SMILES strings to INCHI keys as (a) they are easier for a human to read, and (b) they are much shorter. Here, I initially thought maybe the reason you went for INCHI was that it lent itself better to filenames than SMILES does (since SMILES often contains characters such as "(" which must be escaped). However, I see that INCHI keys also contain characters such as "/" which will pose problems for filenames. **What reason is there to prefer INCHI keys over canonicalized SMILES strings? And how would you deal with the special character issue?**

That said, I do like the introduction of some sort of molecular identifiers as I think this can provide functionality enhancements down the road.

@nividic will raise some other issues in a separate post.

**Comment by halx** [comment]
1. OpenBabel is simply more capable than RDKit when it comes to reading molecule files.  I would therefore like to keep it.  But we can keep it optional such that OB is not a requirement for a functioning code.  If a user wants to use OB for some reason they can activate it themselves or OB could be the default when detected, etc (exact mechanism to be discussed). In this way OB would not need to be a install dependency.

InChi is also available with RDKIT.  It just needs activation at compile time and should be downloaded if necessary.  That's really a responsibility of the maintainer and I don't see why one would not want to compile it in (bar license issues of course).
1. I haven't really thought about the molecule ID because I didn't know what it is used for.  I have chosen the InChi key because it is a hash (of the actual InChi string) and so essentially unique (but if required we can also hash any other information e.g. SMILES).  But obviously you can't really translate it back to a molecule description.  So this all really depends on what the mol ID is eventually used for.

**Comment by halx** [comment]
See #7 ...

**Pull request merged**
